//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaTowarow
    {
        public int Za_ID { get; set; }
        public int To_ID { get; set; }
        public int Li_IloscTowaru { get; set; }
        public decimal Li_Cena_Zakupu { get; set; }
    
        public virtual Towar Towar { get; set; }
        public virtual Zamowienia Zamowienia { get; set; }
    }
}
