//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SklepMuzycznyV2Entities : DbContext
    {
        public SklepMuzycznyV2Entities()
            : base("name=SklepMuzycznyV2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Gatunek> Gatunek { get; set; }
        public DbSet<Klienci> Klienci { get; set; }
        public DbSet<ListaTowarow> ListaTowarow { get; set; }
        public DbSet<Pracownicy> Pracownicy { get; set; }
        public DbSet<Towar> Towar { get; set; }
        public DbSet<Typ> Typ { get; set; }
        public DbSet<Utwor> Utwor { get; set; }
        public DbSet<Wykonawca> Wykonawca { get; set; }
        public DbSet<Zamowienia> Zamowienia { get; set; }
    
        public virtual ObjectResult<Zad1_Result> Zad1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad1_Result>("Zad1");
        }
    
        public virtual ObjectResult<Zad10_Result> Zad10()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad10_Result>("Zad10");
        }
    
        public virtual ObjectResult<Zad11_Result> Zad11()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad11_Result>("Zad11");
        }
    
        public virtual ObjectResult<Nullable<int>> Zad2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Zad2");
        }
    
        public virtual ObjectResult<Zad3_Result> Zad3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad3_Result>("Zad3");
        }
    
        public virtual ObjectResult<Zad4_Result> Zad4()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad4_Result>("Zad4");
        }
    
        public virtual ObjectResult<Zad5_Result> Zad5()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad5_Result>("Zad5");
        }
    
        public virtual ObjectResult<Zad6_Result> Zad6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad6_Result>("Zad6");
        }
    
        public virtual ObjectResult<Zad7_Result> Zad7()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad7_Result>("Zad7");
        }
    
        public virtual ObjectResult<Zad8_Result> Zad8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad8_Result>("Zad8");
        }
    
        public virtual ObjectResult<Zad9_Result> Zad9()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zad9_Result>("Zad9");
        }
    }
}
