//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Towar
    {
        public Towar()
        {
            this.ListaTowarow = new HashSet<ListaTowarow>();
            this.Utwor = new HashSet<Utwor>();
            this.Wykonawca = new HashSet<Wykonawca>();
        }
    
        public int ID { get; set; }
        public int Ga_ID { get; set; }
        public int Ty_ID { get; set; }
        public decimal CenaAktualna { get; set; }
        public int IloscNaStanie { get; set; }
        public string Nazwa { get; set; }
    
        public virtual Gatunek Gatunek { get; set; }
        public virtual ICollection<ListaTowarow> ListaTowarow { get; set; }
        public virtual Typ Typ { get; set; }
        public virtual ICollection<Utwor> Utwor { get; set; }
        public virtual ICollection<Wykonawca> Wykonawca { get; set; }
    }
}
