//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utwor
    {
        public int Ut_ID { get; set; }
        public int To_ID { get; set; }
        public string Ut_Name { get; set; }
        public Nullable<System.DateTime> Ut_CzasUtworu { get; set; }
    
        public virtual Towar Towar { get; set; }
    }
}
